site_name: N0rth5ea's Blog
copyright: Copyright &copy; 2023 - 2025 N0rth5ea
site_description: 涅伽尔该清灰了
site_author: N0rth5ea
theme:
  name: material
  logo: images/logo.png
  features:
    - content.code.copy # 代码块复制按钮
    - navigation.tabs # 启用导航栏标签页
  # 配置浅色和深色模式
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - include-markdown
  - search
# 导航栏配置
nav:
  - 首页: index.md
  - 学习之路:
      - 逆向基础:
          - 工具集合:
              - IDA Pro: study/reverse/tools/ida_pro.md
              - JADX: study/reverse/tools/JADX.md
              - Frida: study/reverse/tools/frida.md
      - wp集锦:
          - 2025-10:
              - 强网杯2025: study/wp/2025-10/qwb_2025.md
  - EVE小记:
      - 我的EVE之路: eve/my_eve_journey.md
  - 那些年误过的国:
      - MC整合包:
          - 龙之冒险新征程: games/mc/dragon_adventure_new.md
  - 友链: friends.md
