site_name: N0rth5ea's Capsule
copyright: Copyright &copy; 2023 - 2025 N0rth5ea
site_description: 涅伽尔该清灰了
site_author: N0rth5ea
theme:
  name: material
  language: zh
  logo: images/logo.png
  favicon: images/logo.png

  features:
    - content.action.edit             # 编辑此页按钮
    - content.action.view             # 查看源码按钮
    - content.code.annotate           # 代码注释
    - content.code.copy               # 代码块复制按钮
    - navigation.footer               # 页脚上下页导航
    - navigation.instant              # 即时加载
    - navigation.instant.progress     # 加载进度条
    - navigation.tabs                 # 导航栏标签页
    - navigation.tabs.sticky          # 粘性标签页
    - navigation.top                  # 返回顶部按钮
    - navigation.tracking             # 锚点跟踪
    - search.highlight                # 搜索高亮
    - search.share                    # 搜索分享
    - search.suggest                  # 搜索建议
    - toc.follow                      # 目录跟随

  # 配色方案
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # 图标配置
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Markdown 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3

  # PyMdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# 插件配置
plugins:
  - search:
      separator: '[\s\u200b\-]'
      lang:
        - zh
        - en
  - include-markdown

# 导航栏配置
nav:
  - 首页: index.md
  - 学习之路:
      - 逆向基础:
          - 工具集合:
              - IDA Pro: study/reverse/tools/ida_pro.md
              - JADX: study/reverse/tools/JADX.md
              - Frida: study/reverse/tools/frida.md
      - wp集锦:
          - 2025-10:
              - 强网杯2025: study/wp/2025-10/qwb_2025.md
      - 杂货铺: study/miscellaneous.md
  - EVE小记:
      - 我的EVE之路: eve/my_eve_journey.md
  - 那些年误过的国:
      - MC整合包:
          - FTB Skies: games/mc/ftb_skies.md
          - 龙之冒险新征程: games/mc/dragon_adventure_new.md
  - 杂谈:
      - 2025-10:
          - ？？？: misc/2025-10/unknown.md
  - 友链: friends.md
