name: Deploy MkDocs

on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize Markdown leading indent
        run: |
          find . -type f -name '*.md' -print0 \
            | xargs -0 -r perl -i -pe 's/^\s{3}(?!\s)/    /'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create CNAME file
        run: echo "blog.n0rth5ea.online" > CNAME

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1 || true

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy