name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Normalize Markdown leading indent
        run: |
          find . -type f -name '*.md' -print0 \
            | xargs -0 -r perl -i -pe 's/^\s{3}(?!\s)/    /'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-include-markdown-plugin

      # 使用 mkdocs gh-deploy 并显式写入 CNAME，防止每次覆盖时丢失自定义域
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --cname blog.n0rth5ea.online